# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17c229a5cdcda9d59de5401d9a8f2ac23e2530bb4ad7362b94d2215af5c04ce68d4ab2eb18920c82540b0218ed4544069e682ba92a3de684baaf44de08b21525

test:
  secret_key_base: a758bf955c8a883794b45db939b681ee982e652c441b41fbc3d797aa72633703e8bef198501b5bc10b2ddcb482fd0fa6a02cf618fd7770b031f80f92b2298e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
